version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_geo
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pollution_monitoring
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: backend_geo
    environment:
      - PYTHONPATH=/app/app
      - DATABASE_URL=postgresql://myuser:mypassword@postgres_geo/pollution_monitoring
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "poetry install --no-root && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    container_name: frontend_geo
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
